# Default values for cog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  pullPolicy: IfNotPresent

## Configure Docker Registry login credentials for private repositories
docker:
    registryEmail:
    registryUser:
    registryPassword:

##
## COG
##
cog:
  name: cog
  serviceType: ClusterIP # If using an Ingress, this must be NodePort
  replicaCount: 1
  image:
    repository: operable/cog
    tag: latest

  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  ingress:
    enabled: false

    # hosts:
    # - cog.example.com

    # annotations:
    #   kubernetes.io/tls-acme: true
    #   kubernetes.io/ingress.class: nginx
    # tls:
    # - hosts:
    #   - cog.example.com
    #   secretName: cog-tls

  ## Chat provider toggle
  ## Only one can be 'true' at a time
  slackEnabled: true
  hipchatEnabled: false

  ## Config values snake-case for templating delimiter
  config:
    ## Hipchat specific configuration
    # cog-hipchat-api-token:
    # cog-hipchat-jabber-id:
    # cog-hipchat-nickname:
    # cog-hipchat-rooms:
    # cog-hipchat-user-api-token:
    # cog-hipchat-user-jabber-ID:
    # cog-hipchat-user-nickname:

    ##
    mix-env: prod

    cog-allow-self-registration: 1
    cog-mqtt-host: 0.0.0.0
    cog-mqtt-port: 1883

    cog-api-url-base: cog.example.com
    ## Cog usually represents these endpoints as separate ports
    ## Configuring the url-base allows them on the same domain
    cog-service-url-base: cog.example.com/service
    cog-trigger-url-base: cog.example.com/trigger

    relay-id: 00000000-0000-0000-0000-000000000000

    ## These variables are used to configure an initial admin account
    # cog-bootstrap-chat-handle:
    cog-bootstrap-username: admin
    cog-bootstrap-email-address: cog@localhost
    cog-bootstrap-first-name: Cog
    cog-bootstrap-last-name: Administrator

    ## send anonymized user data back to Operable
    cog-telemetry: false

  ## Secrets don't like '-'
  secrets:
    slackAPIToken:
    databaseURL: 'ecto://cog:cog@postgresql:5432/cog'
    cogBootstrapPassword:
    cogHipchatJabberPassword:
    cogHipchatUserJabberPassword:

##
## RELAY
##
relay:
  name: relay
  replicaCount: 1
  image:
    repository: operable/relay
    tag: latest

  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  config:
    relay-id: 00000000-0000-0000-0000-000000000000
    relay-managed-dynamic-config: true
    relay-dynamic-config-root: /tmp/bundle_configs
    relay-cog-refresh-interval: 30s
    relay-docker-clean-interval: 1m
    relay-log-level: info

  ## Secrets don't like '-'
  secrets:
    relayCogToken:

nginx:
  name: nginx
  replicaCount: 1
  image:
    repository: nginx
    tag: 1.11
  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceType: LoadBalancer
