apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cog.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  slack-api-token: {{ .Values.cog.secrets.slackAPIToken | b64enc | quote }}
  database-url: {{ .Values.cog.secrets.databaseURL  | b64enc | quote }}
  {{- if .Values.cog.secrets.cogBootstrapPassword }}
  cog-bootstrap-password: {{ .Values.cog.secrets.cogBootstrapPassword | b64enc | quote }}
  {{- else }}
  cog-bootstrap-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.cog.hipchatEnabled }}
  cog-hipchat-jabber-password:
  cog-hipchat-user-jabber-password: 
  {{- end }}
