apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "nginx.fullname" . }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: config
      volumes:
      - name: config
        configMap:
          name: {{ template "nginx.fullname" . }}
          items:
          - key: cog.conf
            path: cog.conf
