apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.nginx.serviceType }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ template "nginx.fullname" . }}
