apiVersion: v1
kind: Secret
metadata:
  name: {{ template "relay.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{- if .Values.relay.secrets.RELAY_COG_TOKEN }}
  RELAY_COG_TOKEN: {{ .Values.relay.secrets.RELAY_COG_TOKEN | b64enc | quote }}
  {{- else }}
  RELAY_COG_TOKEN: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.RELAY_DOCKER_REGISTRY_PASSWORD }}
  RELAY_DOCKER_REGISTRY_PASSWORD: {{ .Values.RELAY_DOCKER_REGISTRY_PASSWORD | b64enc | quote }}
  {{- end }}
